config/routes.rb
DutyHourLogger::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :hourlogs

  root 'static_pages#home'
  match '/signup',	to: 'users#new',                	via: 'get'
  match '/signin',	to: 'sessions#new',            	via: 'get'
  match '/signout',	to: 'sessions#destroy',       	via: 'delete'
  match '/help',		to: 'static_pages#help',     	via: 'get'
  match '/about',	to: 'static_pages#about',    via: 'get'
  match '/contact',	to: 'static_pages#contact',	via: 'get'
  match '/logs',		to: 'hourlogs#index',		via: 'get'

end

app/models/hourlog.rb
class Hourlog < ActiveRecord::Base
	validates :user_id, presence: true
	validates :h_study, presence: true, numericality: true
	validates :h_sleep, presence: true, numericality: true
	validates :logdate, presence: true, :uniqueness => {:scope => :user_id}
	validates :h_lecture, presence: true
	validates :h_mandatory, presence: true
	validates :primary_class, presence: true
	validates :h_extracurriculars, presence: true
	validates :meal, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :hourlogs, dependent: :destroy, order: 'logdate DESC'
	before_save {email.downcase!}
	before_create :create_remember_token
	before_create :create_full_name
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :name, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@louisville.edu/i
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
	validates :password, length: {minimum: 6}
	validates :year, presence: true
	validates :password_confirmation, presence: true

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end

		def create_full_name
			self.name = "#{first_name.capitalize} #{last_name.capitalize}"
			self.sort_name = "#{last_name.capitalize}, #{first_name.capitalize}"
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/hourlogs_controller.rb
class HourlogsController < ApplicationController
	before_action :signed_in_user,		only: [:index, :create]
	before_action :admin_user, 		only: [:index, :destroy]
	before_filter :format_date, 		only: [:create]

	def index
		@hourlogs = Hourlog.all
	end

	def create
		@hourlog = current_user.hourlogs.build(hourlog_params)
		if @hourlog.save
			flash[:success] = "Log created."
			redirect_to root_url
		else
			render 'static_pages/home'
		end
	end

	def destroy
		Hourlog.find(params[:id]).destroy
		flash[:success] = "User destroyed."
		redirect_to hourlogs_url
	end

	private

		def hourlog_params
			params.require(:hourlog).permit(:logdate, :h_study, :h_sleep, :h_lecture, :h_mandatory, :h_extracurriculars, :meal, :anxious, :sad, :depressed, :energy, :hopeless, :sleep_trouble, :awake_trouble, :focus, :no_school, :primary_class, :exercise)
		end

		def format_date
			params[:hourlog][:logdate].to_s
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to root_url
		else
			flash.now[:error] = "Invalid email/password combination."
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@hourlog = current_user.hourlogs.build if signed_in?
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :signed_in_user, 	only: [:index, :show, :edit, :update, :destroy]
	before_action :correct_user, 		only: [:show, :edit, :update]
	before_action :admin_user, 		only: [:index, :destroy]

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@hourlogs = @user.hourlogs
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			sign_in @user
			flash[:success] = "Account Created"
			redirect_to root_url
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated"
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User destroyed."
		redirect_to users_url
	end

	private

		def user_params
			params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :year)
		end

		# Before filters

		def correct_user
			@user = User.find(params[:id])
			redirect_to(root_url) unless current_user?(@user) or current_user.admin?
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	#Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Duty Hour Logger"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

	#Allows table sorting
	def sortable(column, title = nil)
		title ||= column.titleize
		css_class = (column == sort_column) ? "current #{sort_direction}" : nil
		direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
		link_to title, sort: column, direction: direction
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user == current_user
	end

	def signed_in_user
		unless signed_in?
			store_location
			redirect_to signin_url, notice: "Please sign in."
		end
	end

	def admin_user
		redirect_to(root_url) unless current_user.admin?
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hourlogs/_hourlog.html.erb
<li>
	<span class="date">
		<%= hourlog.logdate %>
	</span>
</li>

app/views/hourlogs/index.html.erb
<% provide(:title, 'All logs') %>

<h1>All logs</h1>

<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover dataTable" id="user_table">
<thead>
<tr role="row">
<th>User ID</th>
<th>Date</th>
<th>Study</th>
<th>Sleep</th>
<th>Lecture</th>
<th>Mandatory</th>
<th>Primary Class</th>
<th>Extracurriculars</th>
<th>Meals</th>
<th>Anxious</th>
<th>Sad</th>
<th>Depressed</th>
<th>Lack of Energy</th>
<th>Hopelessness</th>
<th>Trouble Sleeping</th>
<th>Trouble Staying Awake</th>
<th>Trouble Focusing</th>
<th>Fun</th>
<th>Exercise</th>
<th>Delete?</th>
</tr>
</thead>
<tbody>
<% for hourlog in @hourlogs %>
<tr>
<td><%= hourlog.user_id %></td>
<td><%= hourlog.logdate %></td>
<td><%= hourlog.h_study %> hours</td>
<td><%= hourlog.h_sleep %> hours</td>
<td><%= hourlog.h_lecture %> hours</td>
<td><%= hourlog.h_mandatory %> hours</td>
<td><%= hourlog.primary_class %></td>
<td><%= hourlog.h_extracurriculars %> hours</td>
<td><%= hourlog.meal %></td>
<td><%= hourlog.anxious == 1 ? "Yes" : "No" %></td>
<td><%= hourlog.sad == 1 ? "Yes" : "No" %></td>
<td><%= hourlog.depressed == 1 ? "Yes" : "No" %></td>
<td><%= hourlog.energy == 1 ? "Yes" : "No" %></td>
<td><%= hourlog.hopeless == 1 ? "Yes" : "No" %></td>
<td><%= hourlog.sleep_trouble == 1 ? "Yes" : "No" %></td>
<td><%= hourlog.awake_trouble == 1 ? "Yes" : "No" %></td>
<td><%= hourlog.energy == 1 ? "Yes" : "No" %></td>
<td><%= hourlog.no_school == 1 ? "Yes" : "No" %></td>
<td><%= hourlog.exercise == 1 ? "Yes" : "No" %></td>
<td><%=  link_to "delete", hourlog, method: :delete, data: {confirm: "You sure?"}%></td>
</tr>
<% end %>
</tbody>
</table>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    By Zach Strickland
  </small>
  <nav>
    <ul>
    	<li><%= link_to "Help",    help_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Duty Hour Logger", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <% if signed_in? %>
          	<li>
          		<% if current_user.admin?  %>
          		<%= link_to "Data", hourlogs_path %>
          		<% end %>
          	</li>
          	<li>
          		<% if current_user.admin?  %>
          		<%= link_to "Users", users_path %>
          		<% end %>
          	</li>
          	<li id="fat-menu" class="dropdown">
          		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
          			Account <b class="caret"></b>
          		</a>
          		<ul class="dropdown-menu">
          			<li><%= link_to "Profile", current_user %></li>
          			<li><%= link_to "Settings", edit_user_path(current_user) %></li>
          			<li class="divider"></li>
          			<li>
          				<%= link_to "Sign out", signout_path, method: "delete" %>
          			</li>
          		</ul>
          	</li>
          <% else %>
          	<li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>
		</div>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_hourlog_form.html.erb
<%= simple_form_for @hourlog, html: {class: 'form-inline'} do |f| %>
<%= f.error_notification %>
<div class="row-fluid">
	<div class="span12">
		<div class="row-fluid">
			<div class="span4">
			<%= f.input :logdate, wrapper: :prepend, label: "Date of Log:", :as => "string", :input_html => {:class => 'datepicker'} %>
			From waking up yesterday until waking up today, how many hours did you...
			<%= f.input :h_sleep, label: 'Sleep (including naps)?', input_html: {value: f.object.h_sleep || '0'} %>
			<%= f.input :h_study, label: 'Study?', input_html: {value: f.object.h_study || '0'} %>
			<%= f.input :h_lecture, label: 'Spend in lecture (in class, tegrity, pathoma)?', input_html: {value: f.object.h_lecture || '0'} %>
			<%= f.input :h_mandatory, label: 'Spend in mandatory course activities outside of lecture (Sims, TBLs, PBLS, ICC, mandatory preceptorships, 2nd year clinics, etc.)?', input_html: {value: f.object.h_mandatory || '0'} %>
			<%= f.input :h_extracurriculars, label: 'Spend participating in extracurriculars?', input_html: {value: f.object.h_mandatory || '0'} %>
			-- Not necessary for time to equal 24 hours. --
			<p></p>
			<% if current_user.year == 1 %>
				<%= f.input :primary_class, collection: ["Gross Anatomy", "Embryology", "Neuroscience", "ICM 1"], label: 'Which course did you spend the most time on?' %>
			<% end %>
          		<% if current_user.year == 2 %>
          			<%= f.input :primary_class, collection: ["Pathology", "Pharmacology", "Microbiology", "iTBL", "ICM 2"], label: 'Which course did you spend the most time on?' %>
          		<% end %>
			<%= f.input :meal, label: 'How many full meals did you eat?', input_html: {value: f.object.meal || '0'} %>
			</div>
			<div class="span4 offset2">
			In this period have you...
			<%= f.input :anxious, as: :boolean, inline_label: 'felt anxious?', label: false   %>
			<%= f.input :sad, as: :boolean, inline_label: 'felt sad?', label: false   %>
			<%= f.input :depressed, as: :boolean, inline_label: 'felt depressed?', label: false   %>
			<%= f.input :energy, as: :boolean, inline_label: 'felt like you have no energy?', label: false   %>
			<%= f.input :hopeless, as: :boolean, inline_label: 'felt hopeless or helpless?', label: false   %>
			<%= f.input :sleep_trouble, as: :boolean, inline_label: 'had trouble going to sleep?', label: false   %>
			<%= f.input :awake_trouble, as: :boolean, inline_label: 'had trouble staying awake?', label: false   %>
			<%= f.input :focus, as: :boolean, inline_label: 'had trouble focusing?', label: false   %>
			<%= f.input :no_school, as: :boolean, inline_label: 'spent at least 30 minutes on an activity unrelated to school (tv, movie, hobby, etc.)?', label: false   %>
			<%= f.input :exercise, as: :boolean, inline_label: 'spent at least 30 minutes exercising?', label: false   %>
			</div>
		</div>
	<%= f.submit 'Create log', class: 'btn btn-large btn-primary' %>
	</div>
</div>
<% end %>

app/views/shared/_user_info.html.erb
<h1>
	<%= current_user.name %>
</h1>
<span>
	<%= link_to "View completed log dates", current_user %>
</span>
<span>
	<%= pluralize(current_user.hourlogs.count, "logs completed") %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
	This project is seeking to track MS1 and MS2 work hours in order to determine the amount of time spent on school related activities.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>Contact</h1>
<p>
	Contact the administrator by emailing Zach Strickland at zach@Strickland.net.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
	To get help please email Zach Strickland at zach@strickland.net.
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
	<div class="row">
		<aside class="span12">
			<section>
				<%= render 'shared/user_info' %>
			</section>
			<section>
				<%= render 'shared/hourlog_form' %>
			</section>
	</div>
<% else %>
	<div class="center hero-unit">
	  <h1>Medical Student Duty Hour Logger</h1>

	  <h2>

	  </h2>

	  <%= link_to "Sign up now", signup_path, class: "btn btn-large btn-primary" %>
	</div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your account</h1>

<div class="row">
<div class="span6 offset3">
<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm password" %>
<%= f.password_field :password_confirmation %>

<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
<% end %>

</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<h1>All users</h1>

<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover dataTable" id="user_table">
<thead>
<tr role="row">
<th>Name</th>
<th>Email</th>
<th>Year</th>
<th>Delete</th>
</tr>
</thead>
<tbody>
<% for user in @users %>
<tr>
<td><%= link_to user.name, user %></td>
<td><%= user.email %></td>
<td><%= user.year == 1 ? "First Year" : "Second Year" %></td>
<td><% if current_user.admin? && !current_user?(user) %>
<%=  link_to "delete", user, method: :delete, data: {confirm: "You sure?"}%>
<% end %>
</td>
</tr>
<% end %>
</tbody>
</table>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

		<%= f.label :first_name %>
		<%= f.text_field :first_name %>

		<%= f.label :last_name %>
		<%= f.text_field :last_name %>

		<%= f.label :email, "Email (Use your UofL email)" %>
		<%= f.text_field :email %>

		<%= f.label :password %>
		<%= f.password_field :password %>

		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation %>

		<%= f.label :year, "What year are you?" %>
		<%= f.select :year, [['Please select a year', nil], ['First Year', 1], ['Second Year', 2]] %>

		<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= @user.name %>
				<%= @user.email %>
			</h1>
		</section>
	</aside>
	<div class="span8">
		<% if @user.hourlogs.any? %>
		<h3>Logs completed (<%= current_user.hourlogs.count %>)</h3>
		<ol class="hourlogs">
			<%= render @hourlogs %>
		</ol>
		<% end %>
	</div>
</div>